linters:
  enable-all: true
  disable:
    - cyclop
    - funlen
    - gocognit
    - gocyclo
    - goerr113
    - golint
    - interfacer
    - lll
    - maintidx
    - maligned
    - nlreturn
    - scopelint
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
