name: Build
on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # https://github.com/golangci/golangci-lint/releases/tag/v1.45.2
          version: v1.45.2
